// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RFUniverseGrpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RFUniverseGrpc {
  public static partial class RFUniverseGrpcService
  {
    static readonly string __ServiceName = "RFUniverseGrpc.RFUniverseGrpcService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RFUniverseGrpc.Empty> __Marshaller_RFUniverseGrpc_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RFUniverseGrpc.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RFUniverseGrpc.BinaryMessage> __Marshaller_RFUniverseGrpc_BinaryMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RFUniverseGrpc.BinaryMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.Empty> __Method_Link = new grpc::Method<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Link",
        __Marshaller_RFUniverseGrpc_Empty,
        __Marshaller_RFUniverseGrpc_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RFUniverseGrpc.BinaryMessage, global::RFUniverseGrpc.Empty> __Method_CSharpToPythonStream = new grpc::Method<global::RFUniverseGrpc.BinaryMessage, global::RFUniverseGrpc.Empty>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "CSharpToPythonStream",
        __Marshaller_RFUniverseGrpc_BinaryMessage,
        __Marshaller_RFUniverseGrpc_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.BinaryMessage> __Method_PythonToCSharpStream = new grpc::Method<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.BinaryMessage>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PythonToCSharpStream",
        __Marshaller_RFUniverseGrpc_Empty,
        __Marshaller_RFUniverseGrpc_BinaryMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RFUniverseGrpc.RFUniverseGrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RFUniverseGrpcService</summary>
    [grpc::BindServiceMethod(typeof(RFUniverseGrpcService), "BindService")]
    public abstract partial class RFUniverseGrpcServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RFUniverseGrpc.Empty> Link(global::RFUniverseGrpc.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RFUniverseGrpc.Empty> CSharpToPythonStream(grpc::IAsyncStreamReader<global::RFUniverseGrpc.BinaryMessage> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task PythonToCSharpStream(global::RFUniverseGrpc.Empty request, grpc::IServerStreamWriter<global::RFUniverseGrpc.BinaryMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RFUniverseGrpcService</summary>
    public partial class RFUniverseGrpcServiceClient : grpc::ClientBase<RFUniverseGrpcServiceClient>
    {
      /// <summary>Creates a new client for RFUniverseGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RFUniverseGrpcServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RFUniverseGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RFUniverseGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RFUniverseGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RFUniverseGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RFUniverseGrpc.Empty Link(global::RFUniverseGrpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Link(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RFUniverseGrpc.Empty Link(global::RFUniverseGrpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Link, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RFUniverseGrpc.Empty> LinkAsync(global::RFUniverseGrpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LinkAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RFUniverseGrpc.Empty> LinkAsync(global::RFUniverseGrpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Link, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::RFUniverseGrpc.BinaryMessage, global::RFUniverseGrpc.Empty> CSharpToPythonStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CSharpToPythonStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::RFUniverseGrpc.BinaryMessage, global::RFUniverseGrpc.Empty> CSharpToPythonStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_CSharpToPythonStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RFUniverseGrpc.BinaryMessage> PythonToCSharpStream(global::RFUniverseGrpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PythonToCSharpStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RFUniverseGrpc.BinaryMessage> PythonToCSharpStream(global::RFUniverseGrpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PythonToCSharpStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RFUniverseGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RFUniverseGrpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RFUniverseGrpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Link, serviceImpl.Link)
          .AddMethod(__Method_CSharpToPythonStream, serviceImpl.CSharpToPythonStream)
          .AddMethod(__Method_PythonToCSharpStream, serviceImpl.PythonToCSharpStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RFUniverseGrpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Link, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.Empty>(serviceImpl.Link));
      serviceBinder.AddMethod(__Method_CSharpToPythonStream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::RFUniverseGrpc.BinaryMessage, global::RFUniverseGrpc.Empty>(serviceImpl.CSharpToPythonStream));
      serviceBinder.AddMethod(__Method_PythonToCSharpStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::RFUniverseGrpc.Empty, global::RFUniverseGrpc.BinaryMessage>(serviceImpl.PythonToCSharpStream));
    }

  }
}
#endregion
