// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pyrfuniverse/communicator_objects/agent_action.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Robotflow.RFUniverse.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from pyrfuniverse/communicator_objects/agent_action.proto</summary>
  internal static partial class AgentActionReflection {

    #region Descriptor
    /// <summary>File descriptor for pyrfuniverse/communicator_objects/agent_action.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgentActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRweXJmdW5pdmVyc2UvY29tbXVuaWNhdG9yX29iamVjdHMvYWdlbnRfYWN0",
            "aW9uLnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cyKMAQoQQWdlbnRBY3Rp",
            "b25Qcm90bxIhChl2ZWN0b3JfYWN0aW9uc19kZXByZWNhdGVkGAEgAygCEg0K",
            "BXZhbHVlGAQgASgCEhoKEmNvbnRpbnVvdXNfYWN0aW9ucxgGIAMoAhIYChBk",
            "aXNjcmV0ZV9hY3Rpb25zGAcgAygFSgQIAhADSgQIAxAESgQIBRAGQiuqAihS",
            "b2JvdGZsb3cuUkZVbml2ZXJzZS5Db21tdW5pY2F0b3JPYmplY3RzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Robotflow.RFUniverse.CommunicatorObjects.AgentActionProto), global::Robotflow.RFUniverse.CommunicatorObjects.AgentActionProto.Parser, new[]{ "VectorActionsDeprecated", "Value", "ContinuousActions", "DiscreteActions" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class AgentActionProto : pb::IMessage<AgentActionProto> {
    private static readonly pb::MessageParser<AgentActionProto> _parser = new pb::MessageParser<AgentActionProto>(() => new AgentActionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AgentActionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Robotflow.RFUniverse.CommunicatorObjects.AgentActionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AgentActionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AgentActionProto(AgentActionProto other) : this() {
      vectorActionsDeprecated_ = other.vectorActionsDeprecated_.Clone();
      value_ = other.value_;
      continuousActions_ = other.continuousActions_.Clone();
      discreteActions_ = other.discreteActions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AgentActionProto Clone() {
      return new AgentActionProto(this);
    }

    /// <summary>Field number for the "vector_actions_deprecated" field.</summary>
    public const int VectorActionsDeprecatedFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_vectorActionsDeprecated_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> vectorActionsDeprecated_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// mark as deprecated in communicator v1.3.0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> VectorActionsDeprecated {
      get { return vectorActionsDeprecated_; }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 4;
    private float value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "continuous_actions" field.</summary>
    public const int ContinuousActionsFieldNumber = 6;
    private static readonly pb::FieldCodec<float> _repeated_continuousActions_codec
        = pb::FieldCodec.ForFloat(50);
    private readonly pbc::RepeatedField<float> continuousActions_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> ContinuousActions {
      get { return continuousActions_; }
    }

    /// <summary>Field number for the "discrete_actions" field.</summary>
    public const int DiscreteActionsFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_discreteActions_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> discreteActions_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> DiscreteActions {
      get { return discreteActions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AgentActionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AgentActionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!vectorActionsDeprecated_.Equals(other.vectorActionsDeprecated_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value, other.Value)) return false;
      if(!continuousActions_.Equals(other.continuousActions_)) return false;
      if(!discreteActions_.Equals(other.discreteActions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= vectorActionsDeprecated_.GetHashCode();
      if (Value != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value);
      hash ^= continuousActions_.GetHashCode();
      hash ^= discreteActions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      vectorActionsDeprecated_.WriteTo(output, _repeated_vectorActionsDeprecated_codec);
      if (Value != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Value);
      }
      continuousActions_.WriteTo(output, _repeated_continuousActions_codec);
      discreteActions_.WriteTo(output, _repeated_discreteActions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += vectorActionsDeprecated_.CalculateSize(_repeated_vectorActionsDeprecated_codec);
      if (Value != 0F) {
        size += 1 + 4;
      }
      size += continuousActions_.CalculateSize(_repeated_continuousActions_codec);
      size += discreteActions_.CalculateSize(_repeated_discreteActions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AgentActionProto other) {
      if (other == null) {
        return;
      }
      vectorActionsDeprecated_.Add(other.vectorActionsDeprecated_);
      if (other.Value != 0F) {
        Value = other.Value;
      }
      continuousActions_.Add(other.continuousActions_);
      discreteActions_.Add(other.discreteActions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            vectorActionsDeprecated_.AddEntriesFrom(input, _repeated_vectorActionsDeprecated_codec);
            break;
          }
          case 37: {
            Value = input.ReadFloat();
            break;
          }
          case 50:
          case 53: {
            continuousActions_.AddEntriesFrom(input, _repeated_continuousActions_codec);
            break;
          }
          case 58:
          case 56: {
            discreteActions_.AddEntriesFrom(input, _repeated_discreteActions_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
