// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pyrfuniverse/communicator_objects/command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Robotflow.RFUniverse.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from pyrfuniverse/communicator_objects/command.proto</summary>
  internal static partial class CommandReflection {

    #region Descriptor
    /// <summary>File descriptor for pyrfuniverse/communicator_objects/command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9weXJmdW5pdmVyc2UvY29tbXVuaWNhdG9yX29iamVjdHMvY29tbWFuZC5w",
            "cm90bxIUY29tbXVuaWNhdG9yX29iamVjdHMqLQoMQ29tbWFuZFByb3RvEggK",
            "BFNURVAQABIJCgVSRVNFVBABEggKBFFVSVQQAkIrqgIoUm9ib3RmbG93LlJG",
            "VW5pdmVyc2UuQ29tbXVuaWNhdG9yT2JqZWN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Robotflow.RFUniverse.CommunicatorObjects.CommandProto), }, null));
    }
    #endregion

  }
  #region Enums
  internal enum CommandProto {
    [pbr::OriginalName("STEP")] Step = 0,
    [pbr::OriginalName("RESET")] Reset = 1,
    [pbr::OriginalName("QUIT")] Quit = 2,
  }

  #endregion

}

#endregion Designer generated code
