// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pyrfuniverse/communicator_objects/space_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Robotflow.RFUniverse.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from pyrfuniverse/communicator_objects/space_type.proto</summary>
  internal static partial class SpaceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for pyrfuniverse/communicator_objects/space_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpaceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJweXJmdW5pdmVyc2UvY29tbXVuaWNhdG9yX29iamVjdHMvc3BhY2VfdHlw",
            "ZS5wcm90bxIUY29tbXVuaWNhdG9yX29iamVjdHMqLgoOU3BhY2VUeXBlUHJv",
            "dG8SDAoIZGlzY3JldGUQABIOCgpjb250aW51b3VzEAFCK6oCKFJvYm90Zmxv",
            "dy5SRlVuaXZlcnNlLkNvbW11bmljYXRvck9iamVjdHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Robotflow.RFUniverse.CommunicatorObjects.SpaceTypeProto), }, null));
    }
    #endregion

  }
  #region Enums
  internal enum SpaceTypeProto {
    [pbr::OriginalName("discrete")] Discrete = 0,
    [pbr::OriginalName("continuous")] Continuous = 1,
  }

  #endregion

}

#endregion Designer generated code
