// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pyrfuniverse/communicator_objects/unity_to_external.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Robotflow.RFUniverse.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from pyrfuniverse/communicator_objects/unity_to_external.proto</summary>
  internal static partial class UnityToExternalReflection {

    #region Descriptor
    /// <summary>File descriptor for pyrfuniverse/communicator_objects/unity_to_external.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityToExternalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjlweXJmdW5pdmVyc2UvY29tbXVuaWNhdG9yX29iamVjdHMvdW5pdHlfdG9f",
            "ZXh0ZXJuYWwucHJvdG8SFGNvbW11bmljYXRvcl9vYmplY3RzGjVweXJmdW5p",
            "dmVyc2UvY29tbXVuaWNhdG9yX29iamVjdHMvdW5pdHlfbWVzc2FnZS5wcm90",
            "bzJ2ChRVbml0eVRvRXh0ZXJuYWxQcm90bxJeCghFeGNoYW5nZRInLmNvbW11",
            "bmljYXRvcl9vYmplY3RzLlVuaXR5TWVzc2FnZVByb3RvGicuY29tbXVuaWNh",
            "dG9yX29iamVjdHMuVW5pdHlNZXNzYWdlUHJvdG8iAEIrqgIoUm9ib3RmbG93",
            "LlJGVW5pdmVyc2UuQ29tbXVuaWNhdG9yT2JqZWN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Robotflow.RFUniverse.CommunicatorObjects.UnityMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
